      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate cheatsheets.json
        run: node scripts/generate-cheatsheets-json.js

      - name: Update README.md
        run: node scripts/update-readme.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add cheatsheets.json README.md
          git diff --cached --quiet || git commit -m "chore: auto-update cheatsheets index and README"
          git push
